//create Proudct
curl -X POST http://127.0.0.1:7000/api/products/create \
  -F "name=Sample Product" \
  -F "description=This is a sample product." \
  -F "price=49.99" \
  -F "quantity=15" \
  -F "image=@/home/mozakk/Pictures/cover.jpeg"
